gv:
  projectlocation: "/project"
  ipv4: "{{ansible_eth0.ipv4.address}}"
  domain: "lab.brtlvrs.lab"
  networks:
    gitea:
      name: "gitea"
    httpd:
      name: "httpd"
    node:
      name: "httpd"
  image:
    build:
      path: "/tmp/" # "{{playbook_dir}}/build" # base path to copy files to for building image