gv:
  projectlocation: "/project"
  ipv4: "{{ansible_eth0.ipv4.address}}"
  domain: "lab.brtlvrs.lab"
  shareddata:
    name: "shareddata"
  networks:
    proxy:
      name: "proxy"
    gitea:
      name: "gitea"
  image:
    build:
      path: "/tmp/" # "{{playbook_dir}}/build" # base path to copy files to for building image