---
- name: display custom variables
  #-- debug task to display custom created variables
  tags:
  - always
  debug:
    var: "{{ item }}"
    verbosity: 1
  loop:
  - "gv"
  - "_obj"
  - "jaeger"

- name: "stop {{_obj.name}} container"
  tags:
    - never
    - stop
  community.docker.docker_container:
    name: "{{_obj.name}}"
    state: stopped
    container_default_behavior: no_defaults

- name: "remove {{_obj.name}} container"
  tags:
    - never
    - rm
  community.docker.docker_container:
    name: "{{_obj.name}}"
    state: absent   
    container_default_behavior: no_defaults

- name: "run {{_obj.name}} container"
  tags:
    - never
    - run
    - run_only
  community.docker.docker_container:
    name: "{{_obj.name}}"
    image: "{{jaeger.image.name}}:{{jaeger.image.tag}}"
    hostname: "{{_obj.name}}"
    domainname: "{{gv.domain}}"
    labels:
      "traefik.enable" : "true"
      "traefik.http.services.jaeger.loadbalancer.server.port" : "16686"
      "traefik.http.routers.jaeger.entrypoints": "websecure"
      "traefik.http.routers.jaeger.rule": "Host(`jaeger.lab.brtlvrs.lab`)"
      "traefik.http.routers.jaeger.service": "jaeger"
      "traefik.docker.network": "proxy"
    ports:
      - 9411:9411
      - 16686:16686
    env:
      COLLECTOR_ZIPKIN_HTTP_PORT: "9411"
    state: started
    recreate: yes
    network_mode: "{{gv.networks.proxy.name}}"
    networks: 
      - name: "{{gv.networks.proxy.name}}"
    purge_networks: yes
    container_default_behavior: no_defaults
    detach: yes
    cleanup: yes
    restart_policy: "unless-stopped"
