---
- name: display custom variables
  #-- debug task to display custom created variables
  tags:
  - always
  debug:
    var: "{{ item }}"
    verbosity: 1
  loop:
  - "gv"
  - "trfk"

- name: "stop treafik container"
  tags:
    - never
    - stop
  community.docker.docker_container:
    name: "traefik"
    state: stopped
    container_default_behavior: no_defaults

- name: "remove treafik container"
  tags:
    - never
    - rm
  community.docker.docker_container:
    name: "traefik"
    state: absent    
    container_default_behavior: no_defaults

- name: template traefik.toml
  tags:
    - run
    - never
  ansible.builtin.template:
    src: "{{item}}.j2"
    dest: "{{gv.projectlocation}}/traefik/{{item}}"
    force: yes
  loop:
    - traefik.toml

- name: "run treafik container"
  tags:
    - never
    - run
    - run_only
  community.docker.docker_container:
    name: "traefik"
    image: "traefik:v2.4"
    hostname: "traefik"
    domainname: "{{gv.domain}}"
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    state: started
    recreate: yes    
    network_mode: "{{gv.networks.proxy.name}}"
    networks: 
      - name: "{{gv.networks.proxy.name}}"
    container_default_behavior: no_defaults
    detach: yes
    cleanup: yes
    labels:
      "traefik.enable" : "true"
      # dashboard
      "traefik.http.routers.rtr_traefik.entrypoints" : "web"
      "traefik.http.routers.rtr_traefik.rule" : "Host(`traefik.lab.brtlvrs.lab`)"
      "traefik.http.routers.rtr_traefik.service" : "api@internal"
 #     "traefik.http.routers.traefik-secure.tls" : "true"
#      "traefik.http.routers.traefik-secure.middlewares" : "traefik-auth"
#      "traefik.http.middlewares.traefik-auth.basicauth.users": "admin:$$apr1$$BPTPf0B4$$3FqWbu77zxeFPXVaIDRlq/"

    restart_policy: "unless-stopped"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock #-- needed for docker provider
      - "{{gv.projectlocation}}/traefik/traefik.yaml:/etc/traefik/traefik.yaml:ro" #-- static traefik configuration
      - "{{gv.projectlocation}}/traefik/dynamic/:/etc/traefik/dynamic/"  #-- dynamic traefik configuration / file provider
      - "{{gv.projectlocation}}/traefik/log/:/log/"
#      - "{{gv.projectlocation}}/traefik/acme.json:/etc/traefik/acme.json" #-- needed for lets encrypt
      - "{{gv.projectlocation}}/traefik/certs/:/certs/:ro" #-- certificates



